apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: argo-events
  namespace: argo-events
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: argo-events
  revisionHistoryLimit: 1
  source:
    path: argo-events
    repoURL: https://github.com/Issif/argo-falco.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
