apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: falco
  namespace: argocd
spec:
  destination:
    namespace: falco
    server: https://kubernetes.default.svc
  project: falco
  revisionHistoryLimit: 1
  source:
    helm:
      releaseName: falco
      valueFiles:
        - values.yaml
    path: falco/resources
    repoURL: https://github.com/Issif/argo-falco.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
