falco:
    falcosidekick:
        enabled: true
        webui:
            enabled: true
        config:
            webhook:
                address: http://webhook-eventsource-svc.argo-events.svc.cluster.local:12000/event
                customHeaders: Source:falco
    falco:
        rulesFile:
            - /etc/falco/k8s_audit_rules.yaml
            - /etc/falco/rules.d/custom-rules.yaml
    customRules:
        custom-rules.yaml: |-
            - macro: spawned_process
            condition: evt.type = execve and evt.dir=<
            - macro: container
            condition: (container.id != host)
            - list: shell_binaries
            items: [ash, bash, csh, ksh, sh, tcsh, zsh, dash]
            - macro: shell_procs
            condition: proc.name in (shell_binaries)
            - macro: never_true
            condition: (evt.num=0)
            - macro: container_entrypoint
            condition: (not proc.pname exists or proc.pname in (runc:[0:PARENT], runc:[1:CHILD], runc, docker-runc, exe, docker-runc-cur))
            - macro: user_expected_terminal_shell_in_container_conditions
            condition: (never_true)
            - rule: Terminal shell in container
            desc: A shell was used as the entrypoint/exec point into a container with an attached terminal.
            condition: >
                spawned_process and container
                and shell_procs and proc.tty != 0
                and container_entrypoint
                and not user_expected_terminal_shell_in_container_conditions
            exceptions:
                - name: proc_name_image_suffix
                fields: [proc.name, container.image.repository]
                comps: [in, endswith]
            output: >
                A shell was spawned in a container with an attached terminal (user=%user.name user_loginuid=%user.loginuid %container.info
                shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline terminal=%proc.tty container_id=%container.id image=%container.image.repository)
            priority: WARNING
            tags: [container, shell, mitre_execution]
