falco:
    falcosidekick:
        enabled: true
        webui:
            enabled: true
        config:
            webhook:
                address: http://webhook-falco-eventsource-svc.svc.cluster.local:12000/falco
                customHeaders: Source:falco
    fakeEventGenerator:
      enabled: false
    falco:
      rulesFile:
        - /etc/falco/falco_rules.yaml
        - /etc/falco/falco_rules.local.yaml
        - /etc/falco/k8s_audit_rules.yaml
        - /etc/falco/rules.d/custom-rules.yaml
    customRules:
      custom-rules.yaml: |-
        - rule: COOKIE tampering detector
          desc: Detect tampering of super precious cookie recipes
          condition: modify and (evt.arg.oldpath startswith '/usr/share/nginx' or evt.arg.path startswith '/usr/share/nginx')
          output: Cookie recipes tampering detected, secure your cookies,(uid=%user.uid container_id=%container.id container_name=%container.name image=%container.image.repository:%container.image.tag %evt.arg.oldpath)
          priority: EMERGENCY
          tags: [importantrecipesalert]
